// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js 约定：.env.local 优先级高于 .env
config({ path: ".env.local" });
config({ path: ".env" }); // fallback

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // 只有生成迁移（prisma migrate diff --from-migrations）时才需要。
    // 平时不设，行为与之前一致 —— 不会连上任何额外的库。
    // 用法：起一个一次性的空 PG，SHADOW_DATABASE_URL=... npx prisma migrate diff ...
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
