-- 7 个业务角色模板（台账 T13）
--
-- 由 scripts/rbac/generate-business-roles.ts 生成，不要手改这个文件。
-- 这些是「岗位应该能做什么」的定义，与平迁进来的 12 个 legacy 角色是两回事。
--
-- ⛔ 只建角色，不动任何账号的分配 —— 现有 51 个账号继续用平迁来的 legacy 角色，
--    由管理员在权限中心里一个一个改过去（决策 4）。因此本迁移**不**动 permVersion，
--    没有人会被踢下线。
--
-- isSystem = false：这些是模板，管理员可以改、可以删、可以复制出变体。
-- ON CONFLICT DO NOTHING：重跑不覆盖管理员已经调过的权限。

INSERT INTO "AppRole" ("id","code","name","description","isSystem","dataScope","permissions","createdAt","updatedAt")
VALUES (gen_random_uuid()::TEXT, 'office_sales', '办公室销售', '录订单、录采购单；不能审批采购', false, 'ALL'::"DataScope", ARRAY['sales.order.read','sales.order.create','sales.order.update','sales.order.delete','sales.order.confirm','sales.order.cancel','sales.order.print','sales.order.dispatch_print','sales.order.read_audit','sales.order.write_audit','sales.order.export','sales.order.delete_line','sales.quotation.access','sales.daily_report.read','sales.discrepancy.read','sales.workbench.read','purchase.order.read','purchase.order.create','purchase.order.update','purchase.order.print','stock.quality.read','dispatch.wave.read','dispatch.driver_slot.read','finance.invoice.read','master.customer.read','master.customer.create','master.customer.update','master.customer.read_detail','master.customer.read_credit','master.customer.read_last_prices','master.product.read','master.product.read_detail','master.product.read_price_history','master.pricelist.read','master.pricelist.print','master.supplier.read','master.uom.read','master.product_template.read','master.product_category.read','print.center.access','page.operator.access','page.print.access','system.mfa.enroll']::TEXT[], NOW(), NOW())
ON CONFLICT ("code") DO NOTHING;

INSERT INTO "AppRole" ("id","code","name","description","isSystem","dataScope","permissions","createdAt","updatedAt")
VALUES (gen_random_uuid()::TEXT, 'senior_sales', '高级销售', '办公室销售的全部，另外直接负责采购（可审批、可收货）', false, 'ALL'::"DataScope", ARRAY['sales.order.read','sales.order.create','sales.order.update','sales.order.delete','sales.order.confirm','sales.order.cancel','sales.order.print','sales.order.dispatch_print','sales.order.read_audit','sales.order.write_audit','sales.order.export','sales.order.delete_line','sales.quotation.access','sales.daily_report.read','sales.discrepancy.read','sales.workbench.read','purchase.order.read','purchase.order.create','purchase.order.update','purchase.order.approve','purchase.order.receive','purchase.order.import','purchase.order.print','purchase.legacy.read','purchase.legacy.create','purchase.suggestion.read','purchase.suggestion.manage','purchase.plan.read','purchase.plan.manage','stock.quality.read','dispatch.wave.read','dispatch.driver_slot.read','finance.invoice.read','master.customer.read','master.customer.create','master.customer.update','master.customer.read_detail','master.customer.read_credit','master.customer.read_last_prices','master.product.read','master.product.read_detail','master.product.read_price_history','master.pricelist.read','master.pricelist.print','master.supplier.read','master.supplier.create','master.supplier.update','master.uom.read','master.product_template.read','master.product_category.read','analytics.sales.read','analytics.purchase.read','print.center.access','page.operator.access','page.print.access','system.mfa.enroll']::TEXT[], NOW(), NOW())
ON CONFLICT ("code") DO NOTHING;

INSERT INTO "AppRole" ("id","code","name","description","isSystem","dataScope","permissions","createdAt","updatedAt")
VALUES (gen_random_uuid()::TEXT, 'sales_manager', '销售经理', '销售 + 采购 + 司机；数据范围限本人及下属', false, 'TEAM'::"DataScope", ARRAY['sales.order.read','sales.order.create','sales.order.update','sales.order.delete','sales.order.confirm','sales.order.cancel','sales.order.print','sales.order.dispatch_print','sales.order.read_audit','sales.order.write_audit','sales.order.export','sales.order.delete_line','sales.quotation.access','sales.daily_report.read','sales.discrepancy.read','sales.workbench.read','purchase.order.read','purchase.order.create','purchase.order.update','purchase.order.approve','purchase.order.receive','purchase.order.import','purchase.order.print','purchase.legacy.read','purchase.legacy.create','purchase.suggestion.read','purchase.suggestion.manage','purchase.plan.read','purchase.plan.manage','stock.quality.read','dispatch.console.access','dispatch.wave.read','dispatch.wave.read_detail','dispatch.wave.create','dispatch.wave.update','dispatch.wave.delete','dispatch.wave.print_log','dispatch.trip.read','dispatch.trip.create','dispatch.trip.update','dispatch.trip.delete','dispatch.trip.print','dispatch.trip.read_verify','dispatch.trip.verify','dispatch.trip.read_returns','dispatch.trip.returns','dispatch.trip.read_discrepancy','dispatch.trip.discrepancy','dispatch.trip.correct_signature','dispatch.driver_slot.read','dispatch.driver_slot.manage','dispatch.driver_summary.read','dispatch.batch_analysis.read','finance.invoice.read','master.customer.read','master.customer.create','master.customer.update','master.customer.read_detail','master.customer.read_credit','master.customer.read_last_prices','master.product.read','master.product.read_detail','master.product.read_price_history','master.pricelist.read','master.pricelist.print','master.supplier.read','master.supplier.create','master.supplier.update','master.uom.read','master.product_template.read','master.product_category.read','analytics.sales.read','analytics.purchase.read','analytics.margin.read','analytics.logistics.read','analytics.commission.read','analytics.report.read','print.center.access','page.operator.access','page.dispatch_console.access','page.print.access','system.user.read','system.mfa.enroll']::TEXT[], NOW(), NOW())
ON CONFLICT ("code") DO NOTHING;

INSERT INTO "AppRole" ("id","code","name","description","isSystem","dataScope","permissions","createdAt","updatedAt")
VALUES (gen_random_uuid()::TEXT, 'warehouse_manager', '仓库经理', '卸货、质检、配货出库、库存管理', false, 'ALL'::"DataScope", ARRAY['sales.order.read','purchase.order.read','purchase.order.receive','purchase.order.print','purchase.legacy.read','purchase.legacy.create','stock.receipt.read','stock.receipt.create','stock.receipt.confirm','stock.quality.read','stock.quality.manage','stock.pick.read','stock.pick.manage','stock.pick.read_pallets','stock.pick.manage_pallets','stock.move.read','stock.move.create','stock.take.read','stock.take.create','stock.take.update','stock.lot.read','stock.lot.manage','stock.zone.read','stock.zone.manage','stock.scrap.read','stock.scrap.manage','dispatch.wave.read','dispatch.wave.read_detail','master.product.read','master.product.read_detail','master.product.read_price_history','master.uom.read','master.uom_category.read','master.product_template.read','master.product_category.read','analytics.inventory.read','page.warehouse.access','system.mfa.enroll','system.notification.create']::TEXT[], NOW(), NOW())
ON CONFLICT ("code") DO NOTHING;

INSERT INTO "AppRole" ("id","code","name","description","isSystem","dataScope","permissions","createdAt","updatedAt")
VALUES (gen_random_uuid()::TEXT, 'external_sales_staff', '外聘销售', '只录自己的订单；看不到别人的单，也看不到价格表与财务', false, 'OWN'::"DataScope", ARRAY['sales.order.read','sales.order.create','sales.order.update','sales.order.print','sales.order.read_audit','sales.order.write_audit','sales.quotation.access','stock.quality.read','master.customer.read','master.customer.create','master.customer.read_detail','master.customer.read_credit','master.customer.read_last_prices','master.product.read','master.product.read_detail','master.product.read_price_history','master.uom.read','master.product_template.read','master.product_category.read','page.operator.access','system.mfa.enroll']::TEXT[], NOW(), NOW())
ON CONFLICT ("code") DO NOTHING;

INSERT INTO "AppRole" ("id","code","name","description","isSystem","dataScope","permissions","createdAt","updatedAt")
VALUES (gen_random_uuid()::TEXT, 'dispatch_center', '配送中心', '排波次、派车、跟车；不碰订单内容与价格', false, 'ALL'::"DataScope", ARRAY['sales.order.read','sales.order.assign_batch','sales.order.mark_printed','sales.order.dispatch_print','sales.discrepancy.read','sales.discrepancy.manage','stock.quality.read','stock.quality.manage','stock.pick.read','stock.pick.manage','stock.pick.read_pallets','stock.pick.manage_pallets','dispatch.console.access','dispatch.wave.read','dispatch.wave.read_detail','dispatch.wave.create','dispatch.wave.update','dispatch.wave.delete','dispatch.wave.print_log','dispatch.trip.read','dispatch.trip.create','dispatch.trip.update','dispatch.trip.delete','dispatch.trip.print','dispatch.trip.read_verify','dispatch.trip.verify','dispatch.trip.read_returns','dispatch.trip.returns','dispatch.trip.read_discrepancy','dispatch.trip.discrepancy','dispatch.trip.correct_signature','dispatch.driver_slot.read','dispatch.driver_slot.manage','dispatch.driver_summary.read','dispatch.batch_analysis.read','master.customer.read','master.product.read','analytics.logistics.read','print.center.access','tool.geo.use','page.dispatch_console.access','page.print.access','system.mfa.enroll']::TEXT[], NOW(), NOW())
ON CONFLICT ("code") DO NOTHING;

INSERT INTO "AppRole" ("id","code","name","description","isSystem","dataScope","permissions","createdAt","updatedAt")
VALUES (gen_random_uuid()::TEXT, 'print_center', '打印中心', '只打单：拣货单、配送单、发票的打印视图', false, 'ALL'::"DataScope", ARRAY['sales.order.read','sales.order.mark_printed','sales.order.print','sales.order.dispatch_print','dispatch.wave.read','dispatch.wave.read_detail','dispatch.wave.print_log','dispatch.trip.read','dispatch.trip.print','master.customer.read','master.product.read','print.center.access','page.print.access','system.mfa.enroll']::TEXT[], NOW(), NOW())
ON CONFLICT ("code") DO NOTHING;
