export const DELIVERY_BATCHES: string[] = [
  '1 am AFZAAL',
  '1 am ANDRIUS',
  '1 am ASHWIN',
  '1 am BAO',
  '1 am Moazzam',
  '1 am SEAN',
  '1 am WIT',
  '1 am YIWEI',
  '1 am arif',
  '1 am hansung',
  '1 am kris tom',
  '1 am yang',
  '1 pm AFZAAL',
  '1 pm ANDRIUS',
  '1 pm ARIF',
  '1 pm ASHWIN',
  '1 pm BAO',
  '1 pm Moazzam',
  '1 pm SEAN',
  '1 pm WIT',
  '1 pm YIWEI',
  '1 pm kris tom',
  '1 pm yang',
  '2 am AFZAAL',
  '2 am ANDRIUS',
  '2 am ASHWIN',
  '2 am BAO',
  '2 am Moazzam',
  '2 am SEAN',
  '2 am WIT',
  '2 am YIWEI',
  '2 am arif',
  '2 am kris tom',
  '2 am yang',
  '2 pm AFZAAL',
  '2 pm ANDRIUS',
  '2 pm ASHWIN',
  '2 pm BAO',
  '2 pm Moazzam',
  '2 pm SEAN',
  '2 pm WIT',
  '2 pm YIWEI',
  '2 pm arif',
  '2 pm kris tom',
  '2 pm yang',
  '3 pm AFZAAL',
  '3 pm ANDRIUS',
  '3 pm ASHWIN',
  '3 pm BAO',
  '3 pm Moazzam',
  '3 pm SEAN',
  '3 pm WIT',
  '3 pm YIWEI',
  '3 pm arif',
  '3 pm kris tom',
  '3 pm yang',
  '4 pm AFZAAL',
  '4 pm ANDRIUS',
  '4 pm ASHWIN',
  '4 pm BAO',
  '4 pm Moazzam',
  '4 pm SEAN',
  '4 pm WIT',
  '4 pm YIWEI',
  '4 pm arif',
  '4 pm john',
  '4 pm kris tom',
  '4 pm yang',
  '5 pm AFZAAL',
  '5 pm ANDRIUS',
  '5 pm Moazzam',
  '5 pm SEAN',
  '5 pm WIT',
  '5 pm YIWEI',
  '5 pm yang',
]

export function batchPeriod(batch: string): 'AM' | 'PM' {
  return batch.includes(' am ') ? 'AM' : 'PM'
}
