UPDATE "ProductTemplate" SET name='prok ' WHERE id='cmrmt2agd0032w7yl99z9rown';
UPDATE "ProductTemplate" SET name='Aji CHICKEN & Veg Gyoza (30pc)  600g PKT' WHERE id='cmqn8u7d100dcdmylkp6k2ajj';
UPDATE "ProductTemplate" SET name='My Asia Spring Roll Pastry 8"  20''s CASE' WHERE id='cmrofjvtc005i8vylvg7w5al1';
UPDATE "ProductTemplate" SET name='Bamboo Sushi Mat  24cm PKT' WHERE id='cmqn8uiug00hadmylrlriv55f';
UPDATE "ProductTemplate" SET name='Fresh Lily Bulbs  200g*50 CASE' WHERE id='cmroft4e7038g8vylr9tf71kr';
UPDATE "ProductTemplate" SET name='HT Wei Ji Xian Seasoning  Soy Sauce 750ml Jar' WHERE id='cmqn8wig6015sdmylhj3afxb3';
UPDATE "ProductTemplate" SET name='HS-Yamamotoyama  Sushi Nori  10x50''s' WHERE id='cmrofm7h100y48vyllctmu3cx';
UPDATE "ProductTemplate" SET name='Otafuku Yakisoba Sauce 1.8L(2.15kg)  Big Bottle' WHERE id='cmqn8ym0s01vmdmylj4d18rla';
UPDATE "ProductTemplate" SET name='Shimaya Kombu Dashi Soup Stock 10*(2*500g)  CASE' WHERE id='cmqn8zhnh026gdmyltwor9tjb';
UPDATE "ProductTemplate" SET name='Chuannan Sweet Sour  Crisp Pickled Vegetable 30*62g CASE' WHERE id='cmqn8v74g00pmdmylm46go064';
UPDATE "ProductTemplate" SET name='OK Roasted Duck Boneless  Hungary 16‘s 10KG CASE' WHERE id='cmrofo1bj01hw8vyltb4wz1m1';
UPDATE "ProductTemplate" SET name='shirmp ' WHERE id='cmqn90urg02n8dmyls2gll5i5';
UPDATE "ProductTemplate" SET name='vest ' WHERE id='cmqn90v9502nedmylauublu5s';
UPDATE "ProductTemplate" SET name='Sugar granulated 25Kg  BAG' WHERE id='cmqn8tqa4007idmylczbfzhzc';
UPDATE "ProductTemplate" SET name='L002  Pickled Whole Yellow Radish 20*500g CASE' WHERE id='cmqn8xcjr01g2dmylnoc85qfe';
UPDATE "ProductTemplate" SET name='Leng Sour Green Pickled Mustard  36*350G CASE' WHERE id='cmqn8xj6r01icdmyly2g4n21k';
UPDATE "ProductTemplate" SET name='NONGSHIM NEOGURI  Seafood Ramyun & Spicy 20x120g CASE' WHERE id='cmqn8ydoq01ssdmylo00m5juh';
UPDATE "ProductTemplate" SET name='Otafuku Yakisoba Sauce 6*1.8L(2.15kg)  Big CASE' WHERE id='cmqn8ymib01vsdmylt4cwiui0';
UPDATE "ProductTemplate" SET name='Ottogi Roasted Rice Soup(08342)  16*60g CASE' WHERE id='cmqn8yoad01wedmyllfnck59x';
UPDATE "ProductTemplate" SET name='Roasted White Sesame Seed  *Shirakiku *10*1kg CASE' WHERE id='cmqn8z60f022gdmylqeh4s25v';
UPDATE "ProductTemplate" SET name='Sushi Tray With Lid 400s  PT-0.6 CASE' WHERE id='cmqn8zqpr029kdmylstsdhp8g';
UPDATE "ProductTemplate" SET name='Yamamotoyama  Sushi Nori 10x50sht(125g) CASE' WHERE id='cmqn90qk702lsdmyl3yqkmupc';
UPDATE "ProductTemplate" SET name='KHANUM  Chilli Powder Extra Hot 1KG PKT' WHERE id='cmrofk39800828vyldgnup2zd';
UPDATE "ProductTemplate" SET name='Orange Color  500g JAR' WHERE id='cmqn8ykw001v8dmyli9upxekw';
UPDATE "ProductTemplate" SET name='Kikkoman Takeaway Soy Sauce 5*100''s 8ml  CASE' WHERE id='cmqn8x7dh01eadmyle7xkgyds';
UPDATE "ProductTemplate" SET name='SpringHome Glutinous Rice Ball  Sesame 200g PKT' WHERE id='cmqn8zmo40286dmylsdki8gq8';
UPDATE "ProductTemplate" SET name='BAG  Onion SP. 20kg' WHERE id='cmqn8tmbp0066dmylg90nihb9';
UPDATE "ProductTemplate" SET name='Spring Home TYJ Spring Roll Pastry 10"  PKT' WHERE id='cmqn8zm10027ydmyl255kf6u4';
UPDATE "ProductTemplate" SET name='Spring Home TYJ Spring Roll Pastry 8.5"  PKT' WHERE id='cmqn8zmco0282dmyloabdi4e8';
UPDATE "ProductTemplate" SET name='HK Nissin Cup Noodle - XO Sauce Seafood  24*75g CASE' WHERE id='cmrofrwqq02t28vylnhievb63';
UPDATE "ProductTemplate" SET name='Arawana Buckwheat plus  Noodles 15*1Kg CASE' WHERE id='cmrofryms02tq8vyl7n344rts';
UPDATE "ProductTemplate" SET name='Mr Roasted Duck  Duckfillet 630g PKT' WHERE id='cmrofs3hy02vg8vyl67twp3h9';
UPDATE "ProductTemplate" SET name='ASIAN CHOICE  Black Tiger Shrimp HOSO 31/40 10*700g CASE' WHERE id='cmrofso07032o8vylk3gd4qf3';
UPDATE "ProductTemplate" SET name='GL Dried Red Chilli Crushed(Granules)  20*1KG CASE' WHERE id='cmrofrqw902r08vylnuhdadte';
UPDATE "ProductTemplate" SET name='HS-Hanabi Ready  SALTED** EDAMAME 20x400G' WHERE id='cmrofsqz7033q8vyl7tzgkefm';
UPDATE "ProductTemplate" SET name='GL Dried Red Chilli  Granules 1KG PKT' WHERE id='cmrofrr1y02r28vylme4ovw73';
UPDATE "ProductTemplate" SET name='KHANUM  Chilli Powder Extra Hot 6*1KG CASE' WHERE id='cmrofu1c603k28vylllhpaf5n';
UPDATE "ProductTemplate" SET name='Golden Lotus Thai  Long Grain Brown Rice 1kg PKT' WHERE id='cmroftbo203b08vyloruv2av5';
UPDATE "ProductTemplate" SET name='BLOCK 26/30 Prawn PD  6*800g CASE' WHERE id='cmrofuhv503pw8vylc2xth11b';
UPDATE "ProductTemplate" SET name='SONGA  26/30 Prawn *HLSO* 6*900g CASE' WHERE id='cmrofuizh03qa8vylalmt9sei';
UPDATE "ProductTemplate" SET name='HS-Pickled Yellow Radish Whole  20*500 CASE' WHERE id='cmrofv0fu03wg8vyl3qjpduzw';
UPDATE "ProductTemplate" SET name='*Peeled* Edamame  Soy Bean 500g PKT' WHERE id='cmrofv1du03ws8vylw70k1zie';
UPDATE "ProductTemplate" SET name='Bibigo Rice Cake Sticks  20*500g CASE' WHERE id='cmrofvji404368vyl6qyer2eu';
UPDATE "ProductTemplate" SET name='LL Japanese Style Mochi - Purple Rice Taro  12*120g CASE' WHERE id='cmroftr3d03gg8vylgbwn3j9r';
UPDATE "ProductTemplate" SET name='price difference ' WHERE id='cmrofwoco04hg8vylvk2fj9hw';
UPDATE "ProductTemplate" SET name='Pallet Wrap Clear  PKT' WHERE id='cmqn8yq5a01x0dmylvs4swzcu';
UPDATE "ProductTemplate" SET name='Large SOS Grab Bag Premium 250''s  CASE' WHERE id='cmqn8xip801i6dmylp64jgnsg';
UPDATE "ProductTemplate" SET name='Pallet Wrap  Clear CASE' WHERE id='cmqn8yptp01wwdmyl0abr5vkn';
UPDATE "ProductTemplate" SET name='Heera Garlic Granules  6*1kg CASE' WHERE id='cmrofyl2n055o8vylfapetecd';
UPDATE "ProductTemplate" SET name='*Frozen* ASIAN CHOICE  Lotus Roots Slices 20*500g CASE' WHERE id='cmrofyodo056u8vylerszbz01';
UPDATE "ProductTemplate" SET name='*Frozen* ASIAN CHOICE  Lotus Roots Slices 500g PKT' WHERE id='cmrofyoja056w8vyldre4nd3r';
UPDATE "ProductTemplate" SET name='Edamame (in pod)  25*400g CASE' WHERE id='cmrofysbp05888vylddclr2kv';
UPDATE "ProductTemplate" SET name='JSB 8.5" Spring Roll Pastry  20*550g CASE' WHERE id='cmrofzrht05ko8vyltkubklfp';
UPDATE "ProductTemplate" SET name='JSB Chinese Fried  Dough  10*400g CASE' WHERE id='cmrofzrt805ks8vylqpdj5lne';
UPDATE "ProductTemplate" SET name='Fuji Apple (China)  5KG CASE' WHERE id='cmrofzwu405mk8vylqmq29x97';
UPDATE "ProductTemplate" SET name='MG White Fish Ball- (S) Small ' WHERE id='cmrog00au05ns8vylywpjo6n0';
UPDATE "ProductTemplate" SET name='Frozen Ramen (5 Pcs) 5*650g  Case' WHERE id='cmrog04e205p88vylgx00y3px';
UPDATE "ProductTemplate" SET name='Fuji Apple (China)  9KG CASE' WHERE id='cmroflivi00pq8vylmixkf4r1';
UPDATE "ProductTemplate" SET name='Shirakiku  Yaki Sushi Nori Premium GOLD (50s*130g) PKT' WHERE id='cmrofq3k202648vylpfi04ehi';
UPDATE "ProductTemplate" SET name='Kims Duck Pancakes (6''s*17)  PKT' WHERE id='cmroftso303h08vylk4s96ied';
UPDATE "ProductTemplate" SET name='JW  Lemon-flavored Duck Feet 120*28g CASE' WHERE id='cmrofua0103n48vylw7xtirge';
UPDATE "ProductTemplate" SET name='AUTHENTIC Pork  Gyoza 600g PKT' WHERE id='cmrofvc45040k8vylfardnteb';
UPDATE "ProductTemplate" SET name='JS-HAS Shelled peeled  Soybeans  20*454g CASE' WHERE id='cmrofvle3043u8vylwg4a2wau';
UPDATE "ProductTemplate" SET name='HAS Shelled peeled  Soybeans 454g PKT' WHERE id='cmrofvr8n045w8vyle1pfnfzc';
UPDATE "ProductTemplate" SET name='YQ Preserved Mustard & Vegtables 350g  PKT' WHERE id='cmrofy93f051g8vyl7n2zj1rt';
UPDATE "ProductTemplate" SET name='*PVC* Cling Film300mm*300m  PKT' WHERE id='cmqn8txw700a4dmylggobt7p1';
UPDATE "ProductTemplate" SET name='Pure Kraft SOS Grab Bag (21lb) 125''s  CASE' WHERE id='cmrofstyu034s8vylj6yzfjw4';
UPDATE "ProductTemplate" SET name='Majestic 16 OZ  Noodle Box 500''s CASE' WHERE id='cmroftdpo03bq8vyl6l57kl42';
UPDATE "ProductTemplate" SET name='Bamboo Steamer  Paper 5" 350s'' 20*120g CASE' WHERE id='cmrofvgic04248vylimddo30x';
UPDATE "ProductTemplate" SET name='Free Veg   1KG' WHERE id='cmqn8vx6300ykdmylpwln5645';
UPDATE "ProductTemplate" SET name='Chilli Green XL 400g  PKT' WHERE id='cmqn8v3kc00oedmylb8sxum6o';
UPDATE "ProductTemplate" SET name='Yeo''s Chilli Sauce with Garlic 368g (300ml)  Bottle' WHERE id='cmrofwnkd04h68vylslox59ds';
UPDATE "ProductTemplate" SET name='Mae Ploy Sweet Chilli Sauce  24*285Ml CASE' WHERE id='cmrofr0ld02hq8vylbod4udf7';
UPDATE "ProductTemplate" SET name='ASIAN CHOICE  Black Tiger Shrimp HOSO 31/40 700g PKT' WHERE id='cmrofygtk05468vylf3o4pnj4';
