-- Add missing address fields to Customer table
ALTER TABLE "Customer"
  ADD COLUMN IF NOT EXISTS "street"  TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "street2" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "state"   TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "zip"     TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "country" TEXT NOT NULL DEFAULT '';
